---
title: "Sesión de Clase 1 - MEA"
author: "Luis Edmundo Ramírez"
date: '2022-04-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<h2>Matrices - Filmina 13</h2>

```{r}
#Definiendo Matriz A
A<-matrix(c(2,4,-6,7, 1,3,2,1, -4,3,-5,5),nrow = 3,ncol = 4,byrow=T)
A
dim(A)

#Definiendo Matriz B
B<-matrix(c(0,1,6,-2, 2,3,4,3, -2,1,4,4),nrow = 3,ncol = 4,byrow=T)
B
dim(B)

#Suma de A+B
C<-A+B
C
```

<h2>Producto de Matrices - Filmina 18</h2>
```{r}
#Definiendo Matriz A
A<-matrix(c(2,0,-3,4,1,5),nrow = 2,ncol = 3,byrow=T)
A
dim(A)

#Definiendo Matriz B
B<-matrix(c(7,-1,4,7,2,5,0,-4,-3,1,2,3),nrow = 3,ncol = 4,byrow=T)
B
dim(B)

#Cálculo de AxB
C<-A%*%B
C
```

<h2>Producto de Matrices - Filmina 19</h2>
<i><b>$C_{11}$</b></i>
```{r}
#Definiendo Matriz A
A<-matrix(c(2,0,-3),nrow = 1,ncol = 3,byrow=T)
A
dim(A)

#Definiendo Matriz B
B<-matrix(c(7,2,-3),nrow = 3,ncol = 1,byrow=T)
B
dim(B)

#Definiendo Matriz C
C<-A%*%B
C
```

<i><b>$C_{12}$</b></i>
```{r}
#Definiendo Matriz A
A<-matrix(c(2,0,-3),nrow = 1,ncol = 3,byrow=T)
A
dim(A)

#Definiendo Matriz B
B<-matrix(c(-1,5,1),nrow = 3,ncol = 1,byrow=T)
B
dim(B)

#Definiendo Matriz C
C<-A%*%B
C
```

<i><b>$C_{13}$</b></i>
```{r}
#Definiendo Matriz A
A<-matrix(c(2,0,-3),nrow = 1,ncol = 3,byrow=T)
A
dim(A)

#Definiendo Matriz B
B<-matrix(c(4,0,2),nrow = 3,ncol = 1,byrow=T)
B
dim(B)

#Definiendo Matriz C
C<-A%*%B
C
```

<i><b>$C_{14}$</b></i>
```{r}
#Definiendo Matriz A
A<-matrix(c(2,0,-3),nrow = 1,ncol = 3,byrow=T)
A
dim(A)

#Definiendo Matriz B
B<-matrix(c(7,-4,3),nrow = 3,ncol = 1,byrow=T)
B
dim(B)

#Definiendo Matriz C
C<-A%*%B
C
```

<i><b>$C_{21}$</b></i>
```{r}
#Definiendo Matriz A
A<-matrix(c(4,1,5),nrow = 1,ncol = 3,byrow=T)
A
dim(A)

#Definiendo Matriz B
B<-matrix(c(7,2,-3),nrow = 3,ncol = 1,byrow=T)
B
dim(B)

#Definiendo Matriz C
C<-A%*%B
C
```

<i><b>$C_{22}$</b></i>
```{r}
#Definiendo Matriz A
A<-matrix(c(4,1,5),nrow = 1,ncol = 3,byrow=T)
A
dim(A)

#Definiendo Matriz B
B<-matrix(c(-1,5,1),nrow = 3,ncol = 1,byrow=T)
B
dim(B)

#Definiendo Matriz C
C<-A%*%B
C
```

<i><b>$C_{23}$</b></i>
```{r}
#Definiendo Matriz A
A<-matrix(c(4,1,5),nrow = 1,ncol = 3,byrow=T)
A
dim(A)

#Definiendo Matriz B
B<-matrix(c(4,0,2),nrow = 3,ncol = 1,byrow=T)
B
dim(B)

#Definiendo Matriz C
C<-A%*%B
C
```


<i><b>$C_{24}$</b></i>
```{r}
#Definiendo Matriz A
A<-matrix(c(4,1,5),nrow = 1,ncol = 3,byrow=T)
A
dim(A)

#Definiendo Matriz B
B<-matrix(c(7,-4,3),nrow = 3,ncol = 1,byrow=T)
B
dim(B)

#Definiendo Matriz C
C<-A%*%B
C
```


